## 『本次練習內容』
#### 運用Keras搭建簡單的Dense Layer與 Convolution2D Layer，使用相同Neurons數量，計算總參數量相差多少。


## 『本次練習目的』
  #### 本次練習主要是要讓各位同學們了解CNN與FC層的參數使用量差異
  #### Convolution2D有許多參數可以設置，之後章節會細談
  #### 不熟Keras的學員們也可以藉此了解NN層的不同搭法

In [1]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import Input, Dense
from keras.models import Model

In [11]:
##輸入照片尺寸==28*28*1
##都用一層，288個神經元

##建造一個一層的CNN層
classifier=Sequential()

# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
pool_size = (2, 2)
# convolution kernel size
kernel_size = (3, 3)

input_shape = (4, 28, 28, 3)

##Kernel size 3*3，用32張，輸入大小28*28*1
classifier.add(Convolution2D(nb_filters, (kernel_size[0], kernel_size[1]),input_shape=input_shape[1:])) #'''32張Kernel，大小為3*3，輸入尺寸為28*28*1'''
##看看model結構
print(classifier.summary())
#'''理解輸出Total params為何==320'''

##建造一個一層的FC層
classifier=Sequential()
##輸入為28*28*1攤平==784
inputs = (4, 28, 28, 1) #Input()#'''輸入尺寸為28*28*1'''
##CNN中用了(3*3*1)*32個神經元，我們這邊也用相同神經元數量
x=Dense(288)(inputs)#'''使用288個神經元'''
model = Model(inputs=inputs, outputs=x)
##看看model結構
print(model.summary())
#'''理解輸出Total params為何==226080'''

##大家可以自己變換設定看看參數變化

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 26, 26, 32)        896       
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________
None


ValueError: Layer dense_3 expects 1 inputs, but it received 4 input tensors. Inputs received: [<tf.Tensor: shape=(), dtype=int32, numpy=288>, <tf.Tensor: shape=(), dtype=int32, numpy=28>, <tf.Tensor: shape=(), dtype=int32, numpy=28>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]